// This file will be auto-generated by Supabase CLI
// Run: npx supabase gen types typescript --project-id xkmirweadwadcikvikdq > src/types/database.types.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      // Tables will be defined after running migrations
    }
  }
}
